[package]
name = "gabby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
image = "0.24.2"
itertools = "0.10.3"
lazy_static = "1.4.0"
rand = "0.8.5"
